### PR TITLE
Interactive example requested in #17

### PR DESCRIPTION
**Pull request by ThomAub**
This is still ongoing work but a first review would be great.

PS: I known it could have been in a separate PR but I fix the linting in the `example/README.md` and change the way images are declared. If it's ok i will do it also for the main `README.md`

### CODE REVIEW

**Comment by ThomAub** [comment]
Euh .. i don't understand why the commit from the other branch are also here ...

**Comment by ThomAub** [comment]
Also I will investigate why is the generated json cannot be parse by the `from_json.rs`.
My intuition in on the fact that i add to manually create the selector that needs to be hashmaps ..

**Comment by mockersf** [comment]
> Euh .. i don't understand why the commit from the other branch are also here ...

did you create your new branch from the existing branch or from master ?

**Comment by ThomAub** [comment]
Yes, if I remember correctly I wasn’t on master when I created the branch ... Will it be harder to merge ?

**Comment by davidB** [comment]
Recreate an other branch from master, and submit an new PR.

**Comment by davidB** [comment]
@ThomAub Feel free to close this PR, after creating the new PR

**Comment by ThomAub** [comment]
Closing this PR as the new one is #20

**Pull request closed without merging**
